language: elixir

elixir:
  - 1.7
  - 1.8
otp_release:
  - 20.3
  - 21.2
sudo: required

services:
  - rabbitmq

cache:
  directories:
    - ~/.mix
    - _build/dev

script:
  - mix test
  - mix dialyzer
  - mix credo
