language: elixir

elixir:
  - 1.6
  - 1.7

otp_release:
  - 20.3
  - 21.1

sudo: required

services:
  - rabbitmq

cache:
  directories:
    - ~/.mix
    - _build/dev

script:
  - mix test
  - mix dialyzer
  - mix credo
