language: elixir

elixir:
  - 1.7
  - 1.8

otp_release:
  - 20.3
  - 21.3

sudo: required

services:
  - rabbitmq

cache:
  directories:
    - ~/.mix
    - _build/dev

script:
  - mix dialyzer
  - mix credo --strict
  - mix test
