language: elixir

elixir:
  - 1.8
  - 1.9

otp_release:
  - 21.3
  - 22.0

sudo: required

services:
  - rabbitmq

cache:
  directories:
    - ~/.mix
    - _build/dev

script:
  - mix dialyzer
  - mix credo --strict
  - mix test
