on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        otp: ['25']
        elixir: ['1.14']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict --all
      - run: mix dialyzer
  test:
    runs-on: ubuntu-latest
    name: Test (OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}})
    strategy:
      matrix:
        otp: ['23', '24', '25']
        elixir: ['1.10', '1.11', '1.12', '1.14']
        exclude:
          - {otp: '24', elixir: '1.10'}
          - {otp: '25', elixir: '1.10'}
    steps:
      - uses: actions/checkout@v2
      - uses: getong/rabbitmq-action@v1.2
        with:
          rabbitmq version: 'latest'
          host port: 5672
          rabbitmq user: 'test'
          rabbitmq password: 'test'
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - uses: actions/cache@v1
        env:
          cache-name: mix
        with:
          path: ~/.mix
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - uses: actions/cache@v1
        env:
          cache-name: build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test
