name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - 'master'

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    name: Test (OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }})
    strategy:
      matrix:
        otp: ["22.3", "23.3", "24.3", "25.1"]
        elixir: ["1.11", "1.12", "1.13", "1.14"]
        exclude:
          - otp: "24.3"
            elixir: "1.11"
          - otp: "25.1"
            elixir: "1.11"
          - otp: "25.1"
            elixir: "1.12"
          - otp: "25.1"
            elixir: "1.13"
          - otp: "22.3"
            elixir: "1.14"
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test

  lint:
    runs-on: ubuntu-latest
    name: Linting
    strategy:
      matrix:
        elixir: ['1.14']
        otp: ['25']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: PLT cache
        uses: actions/cache@v2
        with:
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          path: |
            priv/plts
      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix credo --strict --all
      - run: mix dialyzer --halt-exit-status
